### ISSUE TITLE
An unnecessary or incorrect import statement. 

### ISSUE THREAD

**Issue by yashpote** [meelgroup/EntropyEstimation#1]
The import call "import numpy as median" does not seem to be required. If it is required, I think the right usage is "from numpy import median".

https://github.com/meelgroup/EntropyEstimation/blob/3299a363ebf349485a09afdef3f32bbba911942a/baseline.py#L35

**Comment by priyanka-golia** [comment]
Hi Yash,

Thanks for pointing this out. It was a minor typo. I have fixed it now. :)
